language: node_js
node_js: '8'
cache: yarn
install:
  - yarn install
  - yarn run build
deploy:
  # provider: npm doesn't work for some reason :(
  - provider: script
    skip_cleanup: true
    script: "cp .npmrc.template $HOME/.npmrc && npm publish"
    on:
      repo: cognitive-class-labs/jupyterlab-infoboxes
      branch: master
      tag: true
